### ISSUE TITLE
Next...

### ISSUE THREAD

**Issue by Kflash** [Kflash/boogy#15]
- [ ]  performance
- [ ] code size reduction

**Comment by Kflash** [comment]
@TrySound Do you know what is the best way for checking identity for Symbol() and any knowledge about the new Map() properties with ES7?

**Comment by TrySound** [comment]
Nope. Didn't use es6 lib yet.

**Comment by Kflash** [comment]
and Symbol() identity? Symbols() have been around for a long time

**Comment by TrySound** [comment]
They are es6 too. Why you need to check it? They are always identity by spec, isn't it?

**Comment by Kflash** [comment]
As it is now I'm checking Symbols for loose equality - after the specs, but not found in other algorithms. But seems like with ES7 there are some differences. And the `isConcatSpreadable` and `valueOf` properties have changed...

**Comment by Kflash** [comment]
@TrySound This lib supports now both ES6 and ES7 comparison, but on ES7 in strict mode, and I figured out the rest. It will be solved ASAP.

**Comment by Kflash** [comment]
Solved...
