### ISSUE TITLE
workflow issues

### ISSUE THREAD

**Issue by Kflash** [Kflash/boogy#5]
Currently rollup-plugin-typescript are used as a quick solution. This plugin sucks big time! Swallow all errors etc. Need to rollback to native TS.

Get rid of Rollup too? Seems to be issues with as well.

**Comment by TrySound** [comment]
Whatever you want. Plugin does not swallow errors. There is no type checking. Just transpilling.

**Comment by Kflash** [comment]
Ok. Anyway typecheckhing is the whole point with ts, but not a big thing on
this module. I found a workaround

On Sep 5, 2016 2:57 PM, "Bogdan Chadkin" <notifications@github.com> wrote:

Whatever you want. Plugin does not swallow errors. There is no type
checking. Just transpilling.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/Kflash/boogy/issues/5#issuecomment-244671476>, or mute
the thread

**Comment by Kflash** [comment]
I close this. No more time to work on this and current workflow is ok. The 7 underlying errors hidden by rollup isnt a big deal.
