### ISSUE TITLE
Rollup issue

### ISSUE THREAD

**Issue by Kflash** [Kflash/boogy#6]
@TrySound Is this behaviour normal for Rollup? Look at the .mjs file in the dist folder. It exporting the 
three main functions like this `export {...};`

I guess this mean it has to be imported like this? `import * as x from 'boogy'`, but I guess that will not work

**Comment by Kflash** [comment]
Only solution for this I guess is to avoid support ES modules?

**Comment by TrySound** [comment]
```
export default {
  prop1: 1,
  prop2: 1
};
```
or better
```
import { named1, named2 } from './module.js';
```

**Comment by Kflash** [comment]
If i do that i screw up the main file where im using 3x exports. One
exports for each func

**Comment by TrySound** [comment]
So what's the problem?

**Comment by Kflash** [comment]
The es module will work. The other file will not. Or im thinking wrong?

**Comment by TrySound** [comment]
What's the other file?

**Comment by Kflash** [comment]
Look at this one. That is what I wanted to archieve, but seems imposible.
https://github.com/Kflash/boogy#then-in-your-project

**Comment by TrySound** [comment]
What's impossible here?
http://rollupjs.org/?shareable=JTdCJTIyb3B0aW9ucyUyMiUzQSU3QiUyMmZvcm1hdCUyMiUzQSUyMmNqcyUyMiUyQyUyMm1vZHVsZU5hbWUlMjIlM0ElMjJteUJ1bmRsZSUyMiUyQyUyMmdsb2JhbHMlMjIlM0ElN0IlN0QlN0QlMkMlMjJtb2R1bGVzJTIyJTNBJTVCJTdCJTIybmFtZSUyMiUzQSUyMm1haW4uanMlMjIlMkMlMjJjb2RlJTIyJTNBJTIyZXhwb3J0JTIwZnVuY3Rpb24lMjBtb2QxKCklMjAlN0IlN0QlNUNuJTVDbmV4cG9ydCUyMGZ1bmN0aW9uJTIwbW9kMigpJTIwJTdCJTdEJTVDbiU1Q25leHBvcnQlMjBmdW5jdGlvbiUyMG1vZDMoKSUyMCU3QiU3RCUyMiU3RCU1RCU3RA==

**Comment by TrySound** [comment]
You want destructure exports object. Go on.
You want get names exports. It works fine. `__esModule` is even here for that.

**Comment by Kflash** [comment]
Problem was that it seems not to be possible to import the es module. But I will just let it be as it is.

**Comment by TrySound** [comment]
Of course it's not possible. There's only syntax spec. Nobody made realisation except bundlers. That's why rollup has cjs output format.

**Comment by Kflash** [comment]
So without any changes. How would you import the es module? In your Rollup example you also got this: 
`export { mod1, mod2, mod3 };`

**Comment by Kflash** [comment]
I was looking at how TS transpile the code. Without using Rollup for bundle and export two versions of the library it can be done. On in CommonJS and one for ES modules. The ES module would then be identical to any ES files.

**Comment by Kflash** [comment]
I close this and let it be as it is for now. Othings things to do then this module.
